#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

#define CAMERA_SPEED 30.0f
#define CAMERA_SENSITIVITY 0.1f

#define CAMERA_PITCH 0.0f
#define CAMERA_YAW 0.0f

#define TEX_WIDTH 16
#define TEX_HEIGHT 16

#define CHUNK_WIDTH 32
#define CHUNK_HEIGHT 128

#endif // GAME_CONFIG_H
